"""empty message

Revision ID: a1aef8d35d9e
Revises: 3f93cc0f3940
Create Date: 2023-09-19 15:24:48.283998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1aef8d35d9e'
down_revision = '3f93cc0f3940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_visited', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'cities', ['country_visited'], ['visited'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('country_visited')

    # ### end Alembic commands ###
